# Generated by Django 5.2 on 2025-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2048)),
                ('query_string', models.TextField(blank=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
